export const FETCH_FOODS_TRENDING_REQUEST = "FETCH_FOODS_TRENDING_REQUEST";
export const FETCH_FOODS_TRENDING_SUCCESS = "FETCH_FOODS_TRENDING_SUCCESS";
export const FETCH_FOODS_TRENDING_FAILURE = "FETCH_FOODS_TRENDING_FAILURE";
export const FETCH_COMBO_REQUEST = "FETCH_COMBO_REQUEST";
export const FETCH_COMBO_SUCCESS = "FETCH_COMBO_SUCCESS";
export const FETCH_COMBO_FAILURE = "FETCH_COMBO_FAILURE";
